### ISSUE TITLE
Nested color path not working linearGradient theme

### ISSUE THREAD

**Issue by Wilson-Lim** [nandorojo/dripsy#286] opened 2023-05-08 09:00 UTC
![Screenshot 2023-05-08 at 4 52 36 PM](https://user-images.githubusercontent.com/15623614/236782266-61d75247-e5bc-4cc0-bb92-c224d9e6e487.png)

1. i wonder did i set wrongly , i have been using dripsy since v2,  the gradient type is always not detected.
2. nested color path is not working inside theme.linearGradients.

**Comment by nandorojo** [comment] 2023-05-08 09:02
i think the first issue is a duplicate of #285

**Comment by nandorojo** [comment] 2023-05-16 16:24
Hey @Wilson-Lim, can you try `4.3.1` and see if that fixes it?

**Closed** 2023-05-16 16:27 UTC

**Comment by Wilson-Lim** [comment] 2023-05-22 10:09
i tested, if using colors props, its working, but gradient props which rely on the dripsy's linearGradients theme value is not working 
![image](https://github.com/nandorojo/dripsy/assets/15623614/7e64d32f-c63b-47ab-8006-425682d0c54e)

with above setting,
1. `surface` not working
2. `ball` is working

and 
![image](https://github.com/nandorojo/dripsy/assets/15623614/15256a3a-af77-48f7-aebf-1a01cee1007d)


the gradient props's type does not seems to work correctly yet.
