### ISSUE TITLE
ScrollView TypeScript issue missing following properties

### ISSUE THREAD

**Issue by midrizi** [nandorojo/dripsy#241] opened 2022-10-01 17:38 UTC
I get the following typescript error whenever I use `ScrollView` Component:

> Type '{ children: Element; }' is missing the following properties from type 'Pick<Omit<{ testID?: string; pointerEvents?: "auto" | "none" | "box-none" | "box-only"; style?: StyleProp<ViewStyle>; horizontal?: boolean; hitSlop?: Insets; ... 100 more ...; persistentScrollbar?: boolean; }, keyof StyledProps<...>> & StyledProps<...> & { ...; } & RefAttributes<...>, "key" | ... 1 more ... | keyof ...': stickyHeaderHiddenOnScroll, StickyHeaderComponent, automaticallyAdjustKeyboardInsets, automaticallyAdjustsScrollIndicatorInsetsts(2739)

The issue seems to be in: `node_modules/@dripsy/core/build/components/ScrollView.d.ts` 
line 239, `...keyof import("react-native").ScrollViewProps...`

**Comment by karmatradeDev** [comment] 2022-10-06 18:56
im also experiencing this but on all dripsy components (text Input, Pressable, ScrollView etc..)

**Comment by nandorojo** [comment] 2022-10-07 15:43
hmm i think this might be related to react 18 or something. could you do `yarn why react` and `yarn why @types/react`?

**Comment by nandorojo** [comment] 2022-10-13 20:26
looks like you have react installed twice. can you uninstall xdl?

**Comment by nandorojo** [comment] 2022-10-13 20:27
alternatively try a yarn resolution for react

**Comment by nandorojo** [comment] 2022-11-20 00:04
Are you using NPM or Yarn?

**Comment by RichardLindhout** [comment] 2022-12-03 14:21
I have this on all dripsy components like TextInput, ScrollView after upgrading next + expo

**Comment by nandorojo** [comment] 2023-01-13 00:51
I think this is a duplicate of #260. Please see the workaround there.

**Closed by nandorojo** 2023-01-13 00:51 UTC
