### ISSUE TITLE
Type arguments on `useDripsyTheme`

### ISSUE THREAD

**Issue by cobraz** [nandorojo/dripsy#111] opened 2021-07-19 09:48 UTC
Hello, thanks for this awesome package!

I'm maintaining a type for my theme, and I'd like to assert that type and hopefully without doing type-casting in components.

Maybe it's worth adding something like this?

```typescript
import { Theme } from '@theme-ui/css';
export interface ContextValue<T = Theme> {
    theme: Theme;
}
export declare const useThemeUI: <T>() => ContextValue<T>;
````

Would you be open for an PR?

**Comment by nandorojo** [comment] 2021-07-19 12:53
Hey thanks for the issue.

It's a duplicate of https://github.com/nandorojo/dripsy/issues/72

I wanted this too, it's just a bit complicated since this is a hook that is exported from theme UI.

For now, I recommend just wrapping it with a `useTheme` hook that returns `useThemeUI().theme as MyTheme`.

I know it's worse to cast the types, but if you just do it once in a single wrapper hook, it's not too bad.

I'll see if I can come up with a better solution in the future.

**Comment by nandorojo** [comment] 2021-07-19 12:55
Here's what I have in my app: https://github.com/nandorojo/dripsy/issues/72#issuecomment-828587515

**Comment by nandorojo** [comment] 2021-07-23 21:06
This might be relevant: https://github.com/nandorojo/dripsy/pull/82#issuecomment-885912452

**Closed by nandorojo** 2021-07-23 21:06 UTC

**Comment by cobraz** [comment] 2021-07-29 22:19
Thank you for replying so quickly and showing interest for this issue! 🙏

**Comment by nandorojo** [comment] 2021-09-29 17:18
Types are getting a *major* improvement in v3. See https://github.com/nandorojo/dripsy/pull/124, #72.

**Comment by nandorojo** [comment] 2021-10-06 18:35
Here's a preview of what's in v3...

https://user-images.githubusercontent.com/13172299/136262629-d2fde15a-87fb-4d37-a6ca-64c71aded495.mp4
