### ISSUE TITLE
Responsive variants take precedence over inline sx styles

### ISSUE THREAD

**Issue by cmaycumber** [nandorojo/dripsy#60] opened 2020-11-25 01:52 UTC
# Issue

Works as intended. `DripText` gets the styles `fonts-size: 2px`:
```jsx
const theme = {
  text: {
    primary: {
      fontSize: 40,
    },
  },
}

...

<DripText variant="primary" sx={{ fontSize: 2 }}>
    joi
</DripText>
```

Doesn't work as intended. `DripText` maintains the responsive styles e.i `40px, 50px, 60px`:
```jsx
const theme = {
  text: {
    primary: {
      fontSize: [40, 50, 60],
    },
  },
}

...

<DripText variant="primary" sx={{ fontSize: 2 }}>
    joi
</DripText>
```

## Other notes

* When inline sx `fontSize` is changed to a string value e.i `"2px"` I get the same behavior. 
* Reproduced on example app and in my own applications

**Comment by nandorojo** [comment] 2020-11-25 02:00
I believe this is the same as https://github.com/nandorojo/dripsy/issues/45. I think I know why this is the case. It'll be a bit of a convoluted solution, but the one I wrote on there should fix it. Basically, if there are responsive styles, they need to come beforehand (and be over-written by) subsequent styles. The only (not good) workaround atm is to only use responsive styles in `sx`, and not directly in the theme.

**Comment by nandorojo** [comment] 2020-11-25 02:09
Herein lies the problem: https://github.com/nandorojo/dripsy/blob/fdc3a9833c0823a8a7ed3b7172ba118ea5e269e4/src/css/ssr-component.tsx#L92

The responsive style currently takes precedent. We'd need to rethink that.

As it stands, this:

```jsx
const theme = {
  fontSize: [10, 12]
}

<Text sx={{ fontSize: [0, 1] }}>
  hi
</Text>
```

...produces this array:

```jsx
const responsiveSSRStyles = [{ fontSize: 10 }, { fontSize: 12 }, { fontSize: 12 }, { fontSize: 12 }, { fontSize: 12 }]
```

We then loop through it, and create a fresnel node for each one. The problem is, we're currently giving precedent to responsive styles, _regardless of where they come from._ This is of course unintended, but it will require some clever thinking through to fix.

The reason the lodash functions and such might get tricky is that it isn't totally clear how to merge the array's order vs normal styles. I'll think it through. I think we might need to not merge these styles, and instead, insert them as props in better order.

**Comment by nandorojo** [comment] 2020-11-25 02:11
What happens if you do this inline?

```jsx
const theme = {
  text: {
    primary: {
      fontSize: [40, 50, 60],
    },
  },
}

...

<DripText variant="primary" sx={{ fontSize: [2] }}>
    joi
</DripText>
```

**Comment by cmaycumber** [comment] 2020-11-25 02:22
> My guess? It will solve it. However, it could also negate all the styles from the theme, since we aren't merging the responsive arrays. Merging the arrays themselves could probably me done with lodash (or a simple reduce/map)

You were right. This does solve the issue.

I can probably use that as a workaround in the meantime. I'm going to take a peak at some of the SSR code and see if I can figure anything useful out.

**Comment by cmaycumber** [comment] 2020-11-25 02:54
I seemed to solve is with the following code:

```js
const styleArray = [
    baseStyle,
    multipleVariantsStyle,
    variantStyle,
    nativeStyles,
    superStyle,
  ]

  const stylesObj = styleArray.reduce((r, c) => Object.assign(r, c), {})
  const nonResponsiveStyleKeys = Object.keys(stylesObj).filter(
    (key) => key !== 'responsiveSSRStyles'
  )
  const responsiveStyles = stylesObj.responsiveSSRStyles
  responsiveStyles?.forEach((breakpointStyle, index) => {
    nonResponsiveStyleKeys.forEach((nonResponsiveStyleKey) => {
      if (Object.keys(breakpointStyle).includes(nonResponsiveStyleKey as any)) {
        responsiveStyles[index] = {
          ...breakpointStyle,
          [`${nonResponsiveStyleKey}`]: stylesObj[nonResponsiveStyleKey],
        }
      }
    })
  })

  const styles = () => stylesObj
```

I'm sure this is definitely not the cleanest solution and I'm not sure if it has side effects, but it seems like it is getting the job done by merging the styles with the responsive styles based on the keys that are passed in.

**Comment by nandorojo** [comment] 2020-11-25 15:09
I might be misreading this, so it might make sense for me to test it. But it seems like the creating of `stylesObj` would lead to each `responsiveSSRStyles` to be fully overwritten by the next one if it exists, since the names match. 

Let me know if I'm reading that incorrectly (I'm more used to the spread syntax, so I could be missing something.)

For example, if `nativeStyles` and `superStyle` both have a `responsiveSSRStyles` in them, it seems like the responsive array from `superStyle` would fully overwrite it, rather than merge with the previous one.

**Comment by nandorojo** [comment] 2020-11-25 15:16
In terms of order, precedence should take place based on each item in the array. So a responsive value from `superStyle` should override any style for the same style key before it. It looks like this is just checking if a non-responsive value already exists for a given key, and if it does, use that. I believe this would mean that we wouldn't be able to override theme values with any responsive style props.

I’ll think this one over as well. 

The main question: how do we get styles to cascade in order from top to bottom of `styleArray`, where each style overwrites the previous one, and where we only sometimes have a responsive array?

**Comment by cmaycumber** [comment] 2020-11-25 15:18
> I might be misreading this, so it might make sense for me to test it. But it seems like the creation of stylesObj would lead to each responsiveSSRStyles to be fully overwritten by the next one if it exists since the names match.

I think that `stylesObj` could probably be created the same was as you were previously creating it with the spread. The `object.assign` was just something I was testing and got carried over.

I think that we could take that logic and apply the loops below to it because they are doing most of the work by replacing the nonResponsiveStyle inside each of the responsive styles objects.

I'll try some different style combos and also test some different logic based on your thoughts to see how everything fairs later today.

**Comment by nandorojo** [comment] 2020-11-25 15:20
Sounds good. Yeah, the way l I'm doing it now isn't good, since it's causing that annoying collision. My current method of just assigning the objects only works if at most one of the sources of styles has a responsive array. 

Sounds good! Looking forward to getting this fixed.

**Comment by nandorojo** [comment] 2021-05-18 21:22
Closing since there hasn't been activity here in a while

**Closed by nandorojo** 2021-05-18 21:22 UTC
