### ISSUE TITLE
Missing property shadowOffset

### ISSUE THREAD

**Issue by romanakash** [nandorojo/dripsy#290] opened 2023-05-29 23:11 UTC
<img width="1107" alt="Screenshot 2023-05-30 at 00 09 24" src="https://github.com/nandorojo/dripsy/assets/40427975/eb053cfd-4205-4ac9-a276-ae19dbba076b">

Using dripsy 4.3.3 and typescript v5.

Trying to setup dripsy for first time but autcompletion for styles is also not working. Tried downgrading version but also not working

**Comment by WNemencha** [comment] 2023-06-13 01:15
Getting the exact same error with fresh setup, how to make it works? This lib' looks promising would like to use it :)

**Comment by nandorojo** [comment] 2023-06-13 16:10
sorry missed this, very odd i’ll take a look

**Comment by WNemencha** [comment] 2023-06-15 10:02
<img width="566" alt="image" src="https://github.com/nandorojo/dripsy/assets/40295432/796b466d-887c-455b-ad2b-6c293a75b77a">

Using `dripsy@^4.3.3` default setup (followed the docs)
When hovering it says:

```
Argument of type '(_: unknown) => { display: string; flexDirection: string; alignItems: string; backgroundColor: string[]; height: number; width: string; padding: number; paddingTop: number; }' is not assignable to parameter of type 'Sx | ((props: unknown) => Sx) | undefined'.
  Type '(_: unknown) => { display: string; flexDirection: string; alignItems: string; backgroundColor: string[]; height: number; width: string; padding: number; paddingTop: number; }' is not assignable to type '(props: unknown) => Sx'.
    Type '{ display: string; flexDirection: string; alignItems: string; backgroundColor: string[]; height: number; width: string; padding: number; paddingTop: number; }' is not assignable to type 'Sx'.
      Property 'shadowOffset' is missing in type '{ display: string; flexDirection: string; alignItems: string; backgroundColor: string[]; height: number; width: string; padding: number; paddingTop: number; }' but required in type 'Pick<ViewStyle, "shadowOffset">'.ts(2345)
```

**Comment by nandorojo** [comment] 2023-06-15 12:46
if you create a minimal reproduction i can take a look, it is working on my end for some reason

**Comment by nandorojo** [comment] 2023-06-15 12:47
that makes me think it’s clashing with `@types/react-native` or something like that

**Comment by WNemencha** [comment] 2023-06-15 19:31
Here's a small repro: https://snack.expo.dev/CU-oaWRXw

If you do Ctrl+I (IntelliSense) you will see it only propose a few properties (as seen in the following screenshot), because the project is JS (not TS) in this repro, it does not see the type error

<img width="1507" alt="image" src="https://github.com/nandorojo/dripsy/assets/40295432/c69df966-a2d0-4b8e-ad42-a225225cf101">

**Comment by matifriaz** [comment] 2023-07-03 06:21
I also have this issue with the new dripsy version. Did we find any fix for this @nandorojo ?

**Comment by nandorojo** [comment] 2023-07-03 13:59
Not quite. Is there a link to the github issue reproducing it?

**Comment by WNemencha** [comment] 2023-07-03 14:30
@nandorojo you should be able to download the repro as a ZIP from Snack sent before by clicking the top-right download button => https://snack.expo.dev/CU-oaWRXw

**Comment by nandorojo** [comment] 2023-12-18 17:46
I think you need the latest RN that expo supports and to remove `@types/react-native` to fix this.

**Closed by nandorojo** 2023-12-18 17:46 UTC
