### ISSUE TITLE
Missing intellisense for variants

### ISSUE THREAD

**Issue by Jomik** [nandorojo/dripsy#147] opened 2021-11-11 09:38 UTC
Hey,
I tried following your guides to set up variants for my `Text` component, but it TypeScript refuses to acknowledge the keys under `text` in `MyTheme`.

I noticed that `Text` gets the prop type `StyledProps<'text', never> & TextProps`
Manually updating `never` to `DripsyVariant<'text'>` solves the issue, and gives me correct suggestions.
When looking at the source for `createThemeComponent`, then it seems like that is also the intention:
https://github.com/nandorojo/dripsy/blob/798c6819c01ce4203e585739235b37b7f5b7efe9/packages/core/src/css/create-themed-component.tsx#L20
https://github.com/nandorojo/dripsy/blob/798c6819c01ce4203e585739235b37b7f5b7efe9/packages/core/src/css/types.ts#L287-L290
Has it been built wrong?

I have dumped my files for a repro into a gist: https://gist.github.com/Jomik/faa0f1ca6c7f46ba179c3bdfb60b1d0c

Versions:
```json
{
    "dripsy": "^3.2.1",
    "typescript": "~4.4.4"
}
```

**Comment by nandorojo** [comment] 2021-11-11 13:32
Yeah I think there’s an issue with intellisense for variants. That’s what you mean right?

**Comment by Jomik** [comment] 2021-11-11 13:40
It simply seems like the `Text` component has the wrong type. The second Generic is `StyledProps` is `never` which results in it accepting no values for the `variant` prop.
The type of the prop becomes `undefined`.
So it results in a type error, not simply lack of type narrowing.

**Comment by nandorojo** [comment] 2021-11-11 13:41
Yeah but can you confirm that what I said is the issue you’re dealing with? Like you’re trying to use the variant prop but not getting intellisense, right?

**Comment by Jomik** [comment] 2021-11-11 14:35
The primary issue is that I am getting a type error because the type is not even `string`, it is `undefined`. As a result, I am obviously not getting intellisense either 😊

If I the `variantFallbackType` then the type becomes string. 

I updated the link for the gist, it was invalid for some reason.
https://gist.github.com/Jomik/faa0f1ca6c7f46ba179c3bdfb60b1d0c#file-theme-ts-L18

**Comment by nandorojo** [comment] 2021-11-11 14:40
What type error? Can you include all relevant info like that in this issue?

**Comment by nandorojo** [comment] 2021-11-11 14:41
Why did you set `variantFallbackType: undefined`

**Comment by nandorojo** [comment] 2021-11-11 14:42
I think that would cause this type error, you should leave that to `string & {}` (the default)

I’ll look into the intellisense separately

**Comment by Jomik** [comment] 2021-11-11 15:17
I set it to undefined, to follow https://github.com/nandorojo/dripsy/blob/798c6819c01ce4203e585739235b37b7f5b7efe9/packages/core/src/declarations.ts#L203-L205
If that is unsupported, then I will just set it as you say 😊

**Comment by nandorojo** [comment] 2021-11-11 15:18
Ah got it, I left this undocumented I think

**Comment by nandorojo** [comment] 2021-11-11 16:20
I think I found the issue

**Comment by nandorojo** [comment] 2021-11-11 22:02
@jomik can you try upgrading to canary and lmk if that solves it?

```sh
yarn add dripsy@canary
```

Works for me:

![image](https://user-images.githubusercontent.com/13172299/141375230-79d90ae2-cc6e-4aa0-b5a9-d92c1f002407.png)

![image](https://user-images.githubusercontent.com/13172299/141375278-5cbcac7a-9497-45a8-b46b-16a6caabda5f.png)

**Comment by nandorojo** [comment] 2021-11-11 22:12
PR at #148

**Comment by nandorojo** [comment] 2021-11-11 22:25
PS if you're using gradient too, upgrade that as well

```sh
yarn add dripsy@canary @dripsy/gradient@canary
```

**Comment by Jomik** [comment] 2021-11-12 08:55
Trying to get this canary installed. It installs a '3.4.1-alpha.0' , but I see there is also a '3.5.1-alpha.0'.
Both still give me the issue.
I currently have
```ts
  types: {
    reactNativeTypesOnly: true,
    onlyAllowThemeValues: 'always',
    strictVariants: true,
  },
```
The expected type of `variant` is undefined.
![image](https://user-images.githubusercontent.com/699655/141439172-8c199eec-bb3d-41f9-9d33-6d4269e811b2.png)

**Comment by nandorojo** [comment] 2021-11-12 12:00
Can I see your theme file

**Comment by Jomik** [comment] 2021-11-12 12:15
> Can I see your theme file

Yes! I have updated the gist: https://gist.github.com/Jomik/faa0f1ca6c7f46ba179c3bdfb60b1d0c#file-theme-ts

**Comment by nandorojo** [comment] 2021-11-12 12:17
I’ll look when I’m at my computer at this thanks

**Comment by nandorojo** [comment] 2021-11-12 19:59
Weird. works in the example app locally but not in my app either. will need to see why

**Comment by Jomik** [comment] 2021-11-12 21:46
What happens locally if you explicitly set `never` as the second generic for `StyledProps` locally?

**Comment by nandorojo** [comment] 2021-11-12 23:07
yeah, that just indicates that it isn't properly reading in the theme

**Comment by nandorojo** [comment] 2021-11-12 23:08
Oh yeah I see what you mean...wtf. Okay so it's a build issue. I'm thinking because it's importing from `..`?

This would explain why it works for me locally

<img width="1360" alt="Screen Shot 2021-11-12 at 6 08 42 PM" src="https://user-images.githubusercontent.com/13172299/141593784-bc991c72-b5f5-498e-99e3-fc642198edf5.png">

**Comment by nandorojo** [comment] 2021-11-12 23:14
I think I'm finding where this is facing issues.

**Comment by nandorojo** [comment] 2021-11-12 23:28
<img width="1036" alt="Screen Shot 2021-11-12 at 6 28 38 PM" src="https://user-images.githubusercontent.com/13172299/141595020-57c49098-0fe5-4c85-bf8a-4bc73d728759.png">

This is what the dripsy example sees...

**Comment by nandorojo** [comment] 2021-11-12 23:51
omgggggggg i think (hope) I got it. fucking typescript haha. if this is it, i'll be quite happy haha.

Before:

```ts
export type StyledProps<ThemeKey extends keyof DripsyFinalTheme, Variant = DripsyVariant<ThemeKey>> = {
  as?: ComponentType<any>
  variant?: Variant
  themeKey?: ThemeKey
  sx?: SxProp
  variants?: Variant[]
}
```

After:

```ts
export type StyledProps<ThemeKey extends keyof DripsyFinalTheme> = {
  as?: ComponentType<any>
  variant?: DripsyVariant<ThemeKey>
  themeKey?: ThemeKey
  sx?: SxProp
  variants?: DripsyVariant<ThemeKey>[]
}
```

I think putting a value that gets generated later (`DripsyVariant<ThemeKey>`) as a generic makes it get evaluated upfront, thus resolving in `never`? 🧐

There's a lesson to not try to "memoize" TS generics, and instead compute them inline.

**Comment by nandorojo** [comment] 2021-11-12 23:52
yeah that fixes it for me. fixed in `3.5.2`. thanks for peaking in the built version.

**Closed** 2021-11-12 23:52 UTC

**Comment by nandorojo** [comment] 2021-11-13 00:04
`3.5.3` should also fix this prop for components without a `themeKey`, such as `View`. Man, this was a tough one. all done though 🥳

**Comment by nandorojo** [comment] 2021-11-13 00:05
From my app (not the example app):

<img width="767" alt="Screen Shot 2021-11-12 at 7 05 06 PM" src="https://user-images.githubusercontent.com/13172299/141597125-46ed99f5-e2f8-4f40-afe6-72f515f53971.png"
>

<img width="691" alt="Screen Shot 2021-11-12 at 7 05 28 PM" src="https://user-images.githubusercontent.com/13172299/141597140-e3ee1e38-bc13-49df-bfdf-fa2bd7bc01c3.png">

**Comment by Jomik** [comment] 2021-11-13 13:53
That's amazing! 💪 Yeah. I'm guessing they try to resolve as much as possible to avoid having the cost for consumers, which sucks when you plan on having your users extend on a type. 😅

**Comment by nandorojo** [comment] 2021-11-13 15:40
Yeah, definitely a unique use case. There isn't much content out there for this kind of thing haha. But I know for next time.

**Comment by chakrihacker** [comment] 2021-11-16 09:19
I still see variant issue on Text Component from dripsy. using 3.5.3

**Comment by nandorojo** [comment] 2021-11-16 14:09
Hm weird, it’s working for me. Could you try reproducing on CodeSandbox maybe? 

Do you also have `@dripsy/gradient` installed? If so, make sure to update that too.
