### ISSUE TITLE
Using styled API causes children Inputs to lose focus (May be from re-renders)

### ISSUE THREAD

**Issue by cmaycumber** [nandorojo/dripsy#40] opened 2020-09-27 17:33 UTC
## Description

When using the styled API inputs lose focus preventing the user from typing. 

This does not however happen with the createThemeComponent API.

### Notes

I'm currently using Formik to handle forms with React Native. I'm not sure of the impact of this on the bug.

## Example

Causes inputs to lose focus:
```jsx
const Card = styled(View, {
  themeKey: "cards",
  defaultVariant: "primary",
})({});
```
Doesn't cause inputs to lose focus: 
```jsx
const Card = createThemedComponent(View, {
  themeKey: "cards",
  defaultVariant: "primary",
});
```

**Comment by nandorojo** [comment] 2020-09-27 17:44
Hmm interesting, I’m actually using Formik too so I’m curious about this. Is this a view wrapping an input? I wonder if we could recreate it on code sandbox or something.

**Comment by nandorojo** [comment] 2020-09-27 19:01
I wonder if this is related to https://github.com/necolas/react-native-web/issues/1755 & forwarding refs, which version of RNW are you using?

**Comment by cmaycumber** [comment] 2020-09-27 20:38
I'm currently on ```"react-native-web": "~0.13.7",```, which installed ```0.13.14```.

> Hmm interesting, I’m actually using Formik too so I’m curious about this. Is this a view wrapping an input? I wonder if we could recreate it on code sandbox or something.

The "Card" component was inside of a Formik wrapper with multiple TextInputs. I bet the problem relatively easy to fix since the createThemedComponent API is working without a hitch.

> I wonder if this is related to [necolas/react-native-web#1755](https://github.com/necolas/react-native-web/issues/1755) & forwarding refs, which version of RNW are you using?

That's interesting. That could definitely be the issue. It seems relevant to my installed version of RNW.

**Comment by nandorojo** [comment] 2020-09-27 20:40
I released a `dripsy@styled` version that refactors `styled` to do nothing more than wrap `createThemedComponent`. Can you see if that fixes it?

**Comment by nandorojo** [comment] 2020-09-27 20:43
Not sure how I didn’t think of this sooner. I can move the pure function logic for the `sx` prop directly into `createThemedComponent`. This way, the `styled` component will do zero magic — it will just be for nicer syntax. Besides figuring out the TS suggestions, this should be easy.

**Comment by cmaycumber** [comment] 2020-09-27 20:46
> I released a `dripsy@styled` version that refactors `styled` to do nothing more than wrap `createThemedComponent`. Can you see if that fixes it?

I'll install that right now.

> Not sure how I didn’t think of this sooner. I can move the pure function logic for the `sx` prop directly into `createThemedComponent`. This way, the `styled` component will do zero magic — it will just be for nicer syntax. Besides figuring out the TS suggestions, this should be easy.

That would be the move for sure.

**Comment by cmaycumber** [comment] 2020-09-27 20:57
> I released a `dripsy@styled` version that refactors `styled` to do nothing more than wrap `createThemedComponent`. Can you see if that fixes it?

This version fixed it for me.

**Comment by nandorojo** [comment] 2020-09-28 00:27
Okay cool. Seems like the previous implementation of `styled`, which forwarded refs twice, was the cause. Since there's a bug for that in RNW, and since `styled` is going to get rid of that implementation anyway in favor of putting a pure function option for `defaultStyle` in `createThemedComponent`, I'll close this for now.

**Closed by nandorojo** 2020-09-28 00:27 UTC
