### ISSUE TITLE
Cannot compile project using anchor "HTML" element

### ISSUE THREAD

**Issue by k0pernicus** [nandorojo/dripsy#119] opened 2021-09-15 15:56 UTC
Hi,
Using the `A` "HTML“ element (`<A>my link</A>`) I have an error I do not fully understand:

```
Type '{ children: string; }' is missing the following properties from type 'Pick<TextProps & ClassAttributes<typeof Text>, "ref" | "onLayout" | "testID" | "accessible" | "accessibilityActions" | "accessibilityLabel" | ... 29 more ... | "accessibilityTraits">': accessibilityComponentType, accessibilityTraits
```

I don't have this issue on other elements like `H1`, `H2`, `P`, ...

Is it related to this issue: https://github.com/nandorojo/dripsy/issues/67 ?

Thanks in advance :)

**Comment by nandorojo** [comment] 2021-09-15 15:57
Are you on the latest version?

**Comment by k0pernicus** [comment] 2021-09-15 15:58
I think so: version "2.3.6" on my `yarn.lock`

**Comment by nandorojo** [comment] 2021-09-15 16:37
I see, I think this may be due to an old React Native version or something. I’ll see if I have a hack for it

**Comment by nandorojo** [comment] 2021-09-15 16:38
It is indeed a duplicate of #67 

maybe try this? https://github.com/nandorojo/dripsy/issues/67#issuecomment-766488375

**Comment by k0pernicus** [comment] 2021-09-16 06:59
I will try today, thanks.

**Closed** 2021-09-27 16:42 UTC

**Comment by k0pernicus** [comment] 2021-09-27 16:44
Sorry, just saw the issue closed here...

I tried the solution in #67 but unfortunately it did not worked.  
We dropped the anchor and implemented our own solution as we had to ship very fast our work.

Sorry again for the delay, and thanks again for your work!

**Comment by nandorojo** [comment] 2021-09-27 17:06
Odd, I think it’s from an old version of RN types, either in your project or from one of your deps. No worries though
